[package]
name = "dronoid-client"
version = "0.1.0"
edition = "2024"

[dependencies]
dronoid-protocol = { version = "0.1.0", path = "../protocol" }

bevy = { version = "0.19.1", features = [
    "2d",
    "bevy_ui_widgets",
    "bevy_color",
    "bevy_state",
    "dynamic_linking",
    "debug",
] }
bevy_color = "0.19.1"
bson = { version = "3.1.0", features = ["serde"] }
clap = { version = "4.6.7", features = ["derive", "env"] }
display-info = "0.5.9"
rand = "0.10.3"
rustls = { version = "0.23.45", default-features = false, features = [
    "std",
    "tls12",
    "ring",
] }
tungstenite = { version = "0.30.0", features = ["rustls-tls-webpki-roots"] }
# bevy_state = "0.19.1"
